
<div class="container">
<div class="col-md-2">

</div>
<div class="col-md-8">
<h2> Participantes</h2>

  <form action="/Evento/lista-paticipantes" method="post" id="formNovoArtigos"  >
  <select class="form-control" name= "curso" id="curso">
        <option value="0" selected="selected"> Curso</option>
        <option value="Analise de Sistemas" > Analise de Sistemas</option>
        <option value="Contabilidade" > Contabilidade</option>  
              
  </select>           
          <br>          
  <select class="form-control" name= "ano" id="ano">
        <option value="0" > Ano</option>
        <option value="1" > 2016</option>
        <option value="2" > 2017</option>
        <option value="3" > 2018</option>        
  </select>   <br>
          
          <button type="submit" class="btn btn-principal">Buscar</button>
    
</form>
</div>
</div>