<?php
if (isset($this->view->sucesso)){
    if($this->view->sucesso == true){
        header("Location:/eventos?saveok=1"); exit;
        }} ?>

<!-- Modal -->

        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="adicionarModalLabel">Adicionar Evento</h4>
            </div>
            <div class="modal-body">

            <form action="/evento/novo" method="post" id="formNovoArtigos" class="form-horizontal" role="form"
                  data-bv-feedbackicons-valid="glyphicon glyphicon-ok"
                  data-bv-feedbackicons-invalid="glyphicon glyphicon-remove"
                  data-bv-feedbackicons-validating="glyphicon glyphicon-refresh"
                >
                <div  class="form-cadastro">
                    <h4><i class="glyphicon glyphicon-user"></i> Novo Evento <span class="observacao-usuarios">*Campos obrigatórios</span></h4>
                    <hr>
                    <p>Preencha corretamente os campos abaixo para cadastrar o artigo:</p>
                    
                     <div class="form-group">
                      <label class="col-sm-2 control-label">Combo<span class="asterisco">*</span></label>
                      <div class="col-sm-9">
            <select class="form-control" name= "curso" id="curso">
              <option value="selected" > Combo</option>
              <option value="1" > Combo 1</option>
               <option value="2" > Combo 2</option>
                <option value="3" >Combo 3</option>
          
           </select> 
           </div>  
           </div>
           
                     <div class="form-group">
                      <label class="col-sm-2 control-label">Curso<span class="asterisco">*</span></label>
                      <div class="col-sm-9">
            <select class="form-control" name= "curso" id="curso">
              <option value="Analise e Desenvolvimento de Sistemas" > Analise de Sistemas</option>
               <option value="Contabilidade" > Contabilidade</option>
                <option value="Psicologia" > Psicologia</option>
                 <option value="Administracao" > Administração</option>
           </select> 
           </div>  
           </div>
                    
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Nome do Evento<span class="asterisco">*</span></label>
                        <div class="col-sm-9">
                            <textarea name="nome_evento" placeholder="Nome do Evento" class="form-control"
                                      data-bv-notempty="true"
                                      data-bv-notempty-message="Por favor informe o texto!"
                                required="required"></textarea>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Convidado<span class="asterisco">*</span></label>
                        <div class="col-sm-9">
                            <textarea name="palestrante" placeholder="Convidado" class="form-control"
                                      data-bv-notempty="true"
                                      data-bv-notempty-message="Por favor informe o texto!"
                                required="required"></textarea>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Assunto<span class="asterisco">*</span></label>
                        <div class="col-sm-9">
                            <textarea name="assunto" placeholder="Assunto" class="form-control"
                                      data-bv-notempty="true"
                                      data-bv-notempty-message="Por favor informe o texto!"
                                required="required"></textarea>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Local<span class="asterisco">*</span></label>
                        <div class="col-sm-9">
                            <textarea name="local" placeholder="Local" class="form-control"
                                      data-bv-notempty="true"
                                      data-bv-notempty-message="Por favor informe o texto!"
                                required="required"></textarea>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Data<span class="asterisco">*</span></label>
                        <div class="col-sm-9">
                            <textarea name="data" placeholder="Data" class="form-control"
                                      data-bv-notempty="true"
                                      data-bv-notempty-message="Por favor informe o texto!"
                                required="required"></textarea>
                        </div>
                    </div>
                     <div class="form-group">
                      <label class="col-sm-2 control-label">Ano<span class="asterisco">*</span></label>
                      <div class="col-sm-9">
            <select class="form-control" name= "ano" id="ano">
              <option value="0" > Ano</option>
              <option value="1" > 2016</option>
               <option value="2" > 2017</option>
                <option value="3" > 2018</option>
          
           </select> 
           </div>  
           </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Horário de Início<span class="asterisco">*</span></label>
                        <div class="col-sm-9">
                            <textarea name="horario_inicio" placeholder="Horário de Início" class="form-control"
                                      data-bv-notempty="true"
                                      data-bv-notempty-message="Por favor informe o texto!"
                                required="required"></textarea>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Horário de Termino<span class="asterisco">*</span></label>
                        <div class="col-sm-9">
                            <textarea name="horario_termino" placeholder="Horário de Início" class="form-control"
                                      data-bv-notempty="true"
                                      data-bv-notempty-message="Por favor informe o texto!"
                                required="required"></textarea>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Carga Horária<span class="asterisco">*</span></label>
                        <div class="col-sm-9">
                            <textarea name="carga_horaria" placeholder="Carga Horária" class="form-control"
                                      data-bv-notempty="true"
                                      data-bv-notempty-message="Por favor informe o texto!"
                                required="required"></textarea>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Valor<span class="asterisco">*</span></label>
                        <div class="col-sm-9">
                            <textarea name="valor" placeholder="00,00 " class="form-control"
                                      data-bv-notempty="true"
                                      data-bv-notempty-message="Por favor informe o texto!"
                                required="required"></textarea>
                        </div>
                    </div>
                    
                    
                    
                    <div class="form-group">
                        <div class="col-sm-12" style="padding-right:25px; margin-top: 20px;">
                            <button type="submit" class="btn btn-principal">Confirmar</button>
                            

                        </div>
                    </div>
                </div>
            </form><p></p>

        </div>