<?php
if (isset($this->view->sucesso)){
    if($this->view->sucesso == true){
        header("Location:/eventos?saveok=1"); exit;
        }} ?>

<!-- Modal -->

        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="adicionarModalLabel">Adicionar Evento</h4>
            </div>
            <div class="modal-body">

           
        </div>
