

<style type="text/css">
    
}
</style>
<div class="ab">
    <div class="col-md-9">
            <h3>Eventos</h3>
  <form action="/alunoEvento/novo" method="post" id="formNovoArtigos" >
      
<input type="hidden" name="id" value=" <?php echo $_SESSION['id'] ?>">

<select class="form-control" name= "cod_evento" id="cod_evento">
  <option value="0" selected="selected"> Evento</option>
   <?php foreach ($this->view->objetos as $registro): ?>      
            <?php  $evento = $registro["nome_evento"];?>
           <?php  $cod = $registro["cod_evento"];?>
        
      <option value= "<?php echo $cod ?>" > <?php echo  $evento ?></option>
        <?php endforeach;?>
        
    </select>   
    <br>
    <button type="submit" class="btn btn-principal">Confirmar</button>
    
    </form>


  
    
    
 </div>
 </div>

    
</div>
			
			
                
    

       
    