<style type="text/css">
    .ab {
        
    }
    @media screen and (min-width: 1px) and (max-width: 600px) {
    #teste {
        width: 400px; 
        margin-top: -292px;
        height: 292px;
        margin-left: -2px;
         background-color: #410f70;
    }
       
}
</style>
<div id="teste">    

</div>
<div class="ab">
    <div class=" col-md-9">
            <h3>Certificados</h3>
   <table class="table table-bordered table-hover">
    <thead>
    <tr>
       
        <th>Evento</th>
         <th>Combo</th>
        <th>Download</th>       
     </tr>
    </thead>
    <tbody>
    <?php foreach ($this->view->objetos as $registro): ?>
        <tr>
            
             <td align="left"><?= $registro['nome_evento']; ?></td>
             <td align="left"><?= $registro['nome_evento']; ?></td>
        <td align="left"> <a href="/pdf?cod_aln_evt=<?=$registro['cod_aln_evt'];?>" >                  Certificado
                </a></td>
            
        </tr>


        <!-- Excluir Modal -->
        <div class="modal fade" id="excluirModal-<?=$registro['id'];?>" tabindex="-1" role="dialog" aria-labelledby="excluirModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="excluirModalLabel">Confirmação de Exclusão</h4>
                    </div>
                    <div class="modal-body">
                        <h2>tem certeza que deseja excluir o artigo "<?= $registro['titulo']; ?>"?</h2>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                        <a href="/artigo/delete?id=<?=$registro['id'];?>" class="btn btn-danger">Excluir</a>
                    </div>

                </div>
            </div>
        </div>

        

    <?php endforeach; ?>
    </tbody>
</table>
</div>
