
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Agnaldo</title>

    <!-- Bootstrap core CSS -->
    <link href="/bootstrap-3.3.2/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/base.css" rel="stylesheet">
    <link href="/css/bootstrapValidator.min.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="/bootstrap-3.3.2/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="/bootstrap-3.3.2/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style type="text/css">
.navbar-left {
        width: 20%;
        height: 590px;
        background-color: #410f70;
    }
     .navbar-top {
        width: 100%;
        height: 50px;
        background-color: #410f70;
        margin-top: -20px;
    }


    
@media screen and (min-width: 1px) and (max-width: 600px) {
  .navbar-left {
        margin-top: -8px;
        width: 100%; 
        height: 230px;      
       
    }
    .navbar-top h3 {        
            text-align: center;      
    }
    .navbar-left li a {
        text-align: center;     
        }
        .navbar-top h3 {        
            color: white;             
            padding-top: 10px;    
    }
    
}
@media screen and (min-width: 600px) and (max-width: 1400px) {

.navbar-top h3 {        
            color: white; 
            margin-left: 18px;
            padding-top: 10px;    
    }

    .navbar-left {
        border: solid #410f70 1px;
        width: 209px;
        }  

    }

    .navbar-left li {
        list-style: none;
    }
   .navbar-left li a {
        color: white;
        font-size: 18px;

           }
    
</style>

</head>

<body>

   <!-- Menu principal -->
    <div class="navbar-top"> <h3>Credential Interface</h3>  </div>

   
    <?php if ($_SESSION['id'] !== null):?>

        <div class="navbar-left">  
                <?php $email = 'agnaldobernardojunior@yahoo.com.br'; if ($_SESSION['email'] == $email):?>
                    <?php { ?>
                        <ul class="nav ">
                            <li><a href="/dashboard-Admin"><span class="glyphicon glyphicon-home"> Home</span></a></li> 

                            <li><a href="/eventos"><span class="glyphicon glyphicon-screenshot"> Eventos</span></a></li> 
                            <li><a href="/participantes"><span class="glyphicon glyphicon-list-alt"> Participantes</span></a></li> 
                        </ul>
                    <?php } ?>
                
                <?php else: ?>
                    <ul class="nav">   
                        <li><a href="/dashboard"><span class="glyphicon glyphicon-home"> Home</span></a></li>
                         <li><a href="/dashboard"><span class="glyphicon glyphicon-screenshot"> Eventos</span></a></li>  
                        <li><a href="/listaEvento?id=<?php echo $_SESSION['id'] ?>" <span class="glyphicon glyphicon-folder-open"> Certificados</span></a> </li>
                         
                    </ul>
                <?php endif ?> 
                <ul class="nav">   
                        
                         <li><a href="/logout"><span class="glyphicon glyphicon-cog"> Seu Cadastro</span></a></li>
                        <li><a href="/logout"><span class="glyphicon glyphicon-off"></span></a></li>
                    </ul>   
        </div>   
    <?php endif ?>   
            



<div class="container">
    <div class="starter-template">

       <?php $this->content(); ?> 

    </div>
</div><!-- /.container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="/bootstrap-3.3.2/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="/bootstrap-3.3.2/js/ie10-viewport-bug-workaround.js"></script>
<script src="/js/bootstrapValidator.min.js"></script>
<script language="JavaScript">
    $(document).ready(function() {
        $('#formLogin').bootstrapValidator();
        $('#formEsqueceu').bootstrapValidator();
        $('#formLogin').bootstrapValidator();
        $('#formNovoArtigos').bootstrapValidator();

    });
</script>
</body>
</html>
